language: shell
sudo: required
services:
- docker
script:
- docker build -t williamgoeller/pennlabs_devops_challenge .
deploy:
    provider: script
    script: bash docker_push
    on:
      branch: master