version: "3.7"
services:
  app:
    image: williamgoeller/pennlabs_devops_challenge:latest
    depends_on: 
      - redis
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis
  redis:
    image: "redis:latest"
    container_name: redis
    hostname: redis
    expose:
      - 6379
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"